######################
# project properties #
######################
projectVersion=1.4-SNAPSHOT
groupPackage=io.github.astrapi69
projectSourceCompatibility=21
projectInceptionYear=2022
projectHolderUsername=astrapi69
projectLeaderName=Asterios Raptis
slash=/
colon=:
issuesPath=/issues
projectDescription=Usefull files for the linux os
projectScmProviderDomain=github.com
projectScmProviderUrl=https://github.com/
projectScmGitUrlPrefix=scm:git:git:@
projectScmGitUrlSuffix=.git
projectLicenseName=MIT License
projectLicenseUrl=https://www.opensource.org/licenses/mit-license.php
projectOrganizationName=Asterios Raptis
projectOrganizationUrl=https://astrapi69.github.io/
projectLicenseDistribution=repo
projectIssueManagementSystem=GitHub
projectRepositoriesReleasesRepoUrl=https://oss.sonatype.org/service/local/staging/deploy/maven2/
projectRepositoriesSnapshotsRepoUrl=https://oss.sonatype.org/content/repositories/snapshots
projectRepositoriesReleasesName=Sonatype Nexus Releases
projectRepositoriesSnapshotsName=Sonatype Nexus Snapshots
projectRepositoriesUserNameKey=ossrhUsername
projectRepositoriesPasswordKey=ossrhPassword
projectRepositoriesMavenUrl=https://plugins.gradle.org/m2/
####################################################
# property for Resolve without the versions plugin #
####################################################
nl.littlerobots.vcu.resolver=true
##########################
# for deploy on sonatype #
##########################
systemProp.org.gradle.internal.publish.checksums.insecure=true
#############################
# gradle related properties #
#############################
# Enable the Gradle daemon
org.gradle.daemon=true
# Enable the build cache
org.gradle.caching=true
# Enable parallel execution
org.gradle.parallel=true
# Run Gradle in offline mode
org.gradle.offline=false
# Configure console output
org.gradle.console=auto
# Set the warning mode
org.gradle.warning.mode=summary
# Enable VFS watching for better performance
org.gradle.vfs.watch=true
