set IDES_HOME="%HOME%/ides"
set JDKS_HOME=%DEV_HOME%\jdks
set JDK8_HOME=%JDKS_HOME%\jdk1.8.0_151
set JDK8_EXECUTABLE=%JDK8_HOME%\bin\javaw.exe
set ECLIPSE_VERSION_NAME="lunajee"
set ECLIPSE_HOME="%IDES_HOME%\eclipse\%ECLIPSE_VERSION_NAME%"
set WORKSPACES_HOME="%HOME%\wss"
set WORKSPACE_HOME="%WORKSPACES_HOME%\jaulp-core"
set ECLIPSE_EXECUTABLE="%ECLIPSE_HOME%\eclipse.exe"
set VM_ARGS=-Xms384m -Xmx1024m -XX:PermSize=128M -XX:MaxPermSize=512M
%ECLIPSE_EXECUTABLE% -clean -data %WORKSPACE_HOME% -showlocation -vm %JDK8_EXECUTABLE% vmargs %VM_ARGS%
